/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.rostec.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import ru.rostec.model.Kind;
import ru.rostec.model.KindModel;
import ru.rostec.model.KindSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Kind service. Represents a row in the &quot;ZSKP_Kind&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link KindModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KindImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KindImpl
 * @see Kind
 * @see KindModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class KindModelImpl extends BaseModelImpl<Kind> implements KindModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a kind model instance should use the {@link Kind} interface instead.
	 */
	public static final String TABLE_NAME = "ZSKP_Kind";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "code_", Types.VARCHAR },
			{ "name", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table ZSKP_Kind (id_ LONG not null primary key,code_ VARCHAR(75) null,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ZSKP_Kind";
	public static final String ORDER_BY_JPQL = " ORDER BY kind.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ZSKP_Kind.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(ru.rostec.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.ru.rostec.model.Kind"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(ru.rostec.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.ru.rostec.model.Kind"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Kind toModel(KindSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Kind model = new KindImpl();

		model.setId(soapModel.getId());
		model.setCode(soapModel.getCode());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Kind> toModels(KindSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Kind> models = new ArrayList<Kind>(soapModels.length);

		for (KindSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(ru.rostec.service.util.ServiceProps.get(
				"lock.expiration.time.ru.rostec.model.Kind"));

	public KindModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Kind.class;
	}

	@Override
	public String getModelClassName() {
		return Kind.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Kind, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Kind, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<Kind, Object> attributeGetterFunction = entry.getValue();

			attributes.put(attributeName,
				attributeGetterFunction.apply((Kind)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Kind, Object>> attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Kind, Object> attributeSetterBiConsumer = attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Kind)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Kind, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Kind, Object>> getAttributeSetterBiConsumers() {
		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Kind, Object>> _attributeGetterFunctions;
	private static final Map<String, BiConsumer<Kind, Object>> _attributeSetterBiConsumers;

	static {
		Map<String, Function<Kind, Object>> attributeGetterFunctions = new LinkedHashMap<String, Function<Kind, Object>>();
		Map<String, BiConsumer<Kind, ?>> attributeSetterBiConsumers = new LinkedHashMap<String, BiConsumer<Kind, ?>>();


		attributeGetterFunctions.put(
			"id",
			new Function<Kind, Object>() {

				@Override
				public Object apply(Kind kind) {
					return kind.getId();
				}

			});
		attributeSetterBiConsumers.put(
			"id",
			new BiConsumer<Kind, Object>() {

				@Override
				public void accept(Kind kind, Object id) {
					kind.setId((Long)id);
				}

			});
		attributeGetterFunctions.put(
			"code",
			new Function<Kind, Object>() {

				@Override
				public Object apply(Kind kind) {
					return kind.getCode();
				}

			});
		attributeSetterBiConsumers.put(
			"code",
			new BiConsumer<Kind, Object>() {

				@Override
				public void accept(Kind kind, Object code) {
					kind.setCode((String)code);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<Kind, Object>() {

				@Override
				public Object apply(Kind kind) {
					return kind.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<Kind, Object>() {

				@Override
				public void accept(Kind kind, Object name) {
					kind.setName((String)name);
				}

			});


		_attributeGetterFunctions = Collections.unmodifiableMap(attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap((Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_code = code;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Kind.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Kind toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Kind)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KindImpl kindImpl = new KindImpl();

		kindImpl.setId(getId());
		kindImpl.setCode(getCode());
		kindImpl.setName(getName());

		kindImpl.resetOriginalValues();

		return kindImpl;
	}

	@Override
	public int compareTo(Kind kind) {
		long primaryKey = kind.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Kind)) {
			return false;
		}

		Kind kind = (Kind)obj;

		long primaryKey = kind.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Kind> toCacheModel() {
		KindCacheModel kindCacheModel = new KindCacheModel();

		kindCacheModel.id = getId();

		kindCacheModel.code = getCode();

		String code = kindCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			kindCacheModel.code = null;
		}

		kindCacheModel.name = getName();

		String name = kindCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			kindCacheModel.name = null;
		}

		return kindCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Kind, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((4 * attributeGetterFunctions.size()) +
				2);

		sb.append("{");

		for (Map.Entry<String, Function<Kind, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<Kind, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Kind)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Kind, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((5 * attributeGetterFunctions.size()) +
				4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Kind, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<Kind, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Kind)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Kind.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Kind.class, ModelWrapper.class
		};
	private long _id;
	private String _code;
	private String _name;
	private Kind _escapedModel;
}