/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.rostec.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Kind service. Represents a row in the &quot;ZSKP_Kind&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.rostec.model.impl.KindModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.rostec.model.impl.KindImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Kind
 * @see ru.rostec.model.impl.KindImpl
 * @see ru.rostec.model.impl.KindModelImpl
 * @generated
 */
@ProviderType
public interface KindModel extends BaseModel<Kind> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kind model instance should use the {@link Kind} interface instead.
	 */

	/**
	 * Returns the primary key of this kind.
	 *
	 * @return the primary key of this kind
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kind.
	 *
	 * @param primaryKey the primary key of this kind
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this kind.
	 *
	 * @return the ID of this kind
	 */
	public long getId();

	/**
	 * Sets the ID of this kind.
	 *
	 * @param id the ID of this kind
	 */
	public void setId(long id);

	/**
	 * Returns the code of this kind.
	 *
	 * @return the code of this kind
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this kind.
	 *
	 * @param code the code of this kind
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this kind.
	 *
	 * @return the name of this kind
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this kind.
	 *
	 * @param name the name of this kind
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Kind kind);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Kind> toCacheModel();

	@Override
	public Kind toEscapedModel();

	@Override
	public Kind toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}