/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.rostec.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ZskpProcess service. Represents a row in the &quot;ZSKP_ZskpProcess&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.rostec.model.impl.ZskpProcessModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.rostec.model.impl.ZskpProcessImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ZskpProcess
 * @see ru.rostec.model.impl.ZskpProcessImpl
 * @see ru.rostec.model.impl.ZskpProcessModelImpl
 * @generated
 */
@ProviderType
public interface ZskpProcessModel extends BaseModel<ZskpProcess> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a zskp process model instance should use the {@link ZskpProcess} interface instead.
	 */

	/**
	 * Returns the primary key of this zskp process.
	 *
	 * @return the primary key of this zskp process
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this zskp process.
	 *
	 * @param primaryKey the primary key of this zskp process
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this zskp process.
	 *
	 * @return the uuid of this zskp process
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this zskp process.
	 *
	 * @param uuid the uuid of this zskp process
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the process ID of this zskp process.
	 *
	 * @return the process ID of this zskp process
	 */
	public long getProcessId();

	/**
	 * Sets the process ID of this zskp process.
	 *
	 * @param processId the process ID of this zskp process
	 */
	public void setProcessId(long processId);

	/**
	 * Returns the name of this zskp process.
	 *
	 * @return the name of this zskp process
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this zskp process.
	 *
	 * @param name the name of this zskp process
	 */
	public void setName(String name);

	/**
	 * Returns the type of this zskp process.
	 *
	 * @return the type of this zskp process
	 */
	public long getType();

	/**
	 * Sets the type of this zskp process.
	 *
	 * @param type the type of this zskp process
	 */
	public void setType(long type);

	/**
	 * Returns the kind of this zskp process.
	 *
	 * @return the kind of this zskp process
	 */
	public long getKind();

	/**
	 * Sets the kind of this zskp process.
	 *
	 * @param kind the kind of this zskp process
	 */
	public void setKind(long kind);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ZskpProcess zskpProcess);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ZskpProcess> toCacheModel();

	@Override
	public ZskpProcess toEscapedModel();

	@Override
	public ZskpProcess toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}